---

# dotfiles_repo:
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/git/dot-files
dotfiles_files:
  - name: .zshrc
    src: linux/.zshrc
    dst: .zshrc
  - name: ~/.face
    src: linux/.face
    dst: .face

extra_files:
  - src: files/media/radio_stations.m3u8
    dest: ~/Music/radio_stations.m3u8

apt_repositories:
  - key_url: https://packages.microsoft.com/keys/microsoft.asc
    key_dest: /etc/apt/keyrings/packages.microsoft.asc
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.asc]
      https://packages.microsoft.com/repos/code
      stable
      main
    state: present
    update_cache: true

apt_packages:
  - deb: https://packages.microsoft.com/config/{{ ansible_distribution | lower }}//{{ ansible_distribution_version }}/packages-microsoft-prod.deb
  - deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/obsidian_1.6.7_amd64.deb
    update_cache: true
  - name: audacious
  - name: git
  - name: kate
  - name: neovim
  - name: zsh
  - name: code

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []

pipx_packages:
  - name: mkdocs
    state: present  # present/absent/latest, default: present
    version: "0.16.3"  # default: N/A

snap_packages:
  - name: kfind
    state: present

  - name: kompare
    state: present

  - name: spotify
    state: present

  - name: bruno
    state: present

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/extra-config-openssh-server.yml
