---
collections:
  - name: community.general
  - name: community.docker
roles:
  - name: robertobernabe.dotfiles
    version: main
    src: git@github.com:robertobernabe/ansible-role-dotfiles.git
    scm: git
    # accept_hostkey: true

  - name: geerlingguy.docker
