---
- name: Copy our extra files.
  block:
    - name: Ensure that the dest directory exist.
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
      loop: "{{ extra_files }}"
      become: false

    - name: Copy the files.
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop: "{{ extra_files }}"
      become: false
