---
- name: Making sure that, some packages are already available.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - pipx
    - python3
    - python3-pip
    - python3-venv
  become: true

- name: Adding extra Apt repositories.
  become: true
  block:
    - name: Download and install the public key.
      ansible.builtin.get_url:
        url: "{{ item.key_url }}"
        dest: "{{ item.key_dest }}"
      when: item.key_url is defined
      loop: "{{ apt_repositories }}"

    - name: Add Apt repositories.
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state | default('present') }}"
        update_cache: "{{ item.update_cache | default('no') }}"
      loop: "{{ apt_repositories }}"

- name: Install System Apt packages.
  ansible.builtin.apt:
    name: "{{ item.name | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
    update_cache: "{{ item.update_cache | default('no') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_packages }}"
  become: true

- name: Install Snap packages.
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ snap_packages }}"
  become: true
  tags: molecule-notest  # Skip this task in molecule tests.

- name: Install global Pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
  loop: "{{ pip_packages }}"
  become: false

- name: Install global Python Package through PIPX.
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ pipx_packages }}"
  when: pipx_packages is defined
