---
- name: Install System Apt packages.
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_packages }}"
  become: true

- name: Install Snap packages.
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ snap_packages }}"
  become: true

- name: Install global Pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
  loop: "{{ pip_packages }}"
  become: false

- name: Install global Python Package through PIPX.
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ pipx_packages }}"
  when: pipx_packages is defined
