---
- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Ensure openssh-server is installed.
      package:
        name:
          - openssh-server
        state: present

- name: Include our playbook
  import_playbook: ../../main.yml
