---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    env:
      RUNNING_IN_DOCKER: "true"
      DEBIAN_FRONTEND: "noninteractive"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_ROLES_PATH: ./../../roles-extra/:./../../roles/
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
